const fs = require('fs');

const blind75 = [
  { name: 'Two Sum', difficulty: 'Easy', topic: 'Arrays & Hashing', link: 'https://leetcode.com/problems/two-sum/' },
  { name: 'Best Time to Buy and Sell Stock', difficulty: 'Easy', topic: 'Arrays & Hashing', link: 'https://leetcode.com/problems/best-time-to-buy-and-sell-stock/' },
  { name: 'Contains Duplicate', difficulty: 'Easy', topic: 'Arrays & Hashing', link: 'https://leetcode.com/problems/contains-duplicate/' },
  { name: 'Product of Array Except Self', difficulty: 'Medium', topic: 'Arrays & Hashing', link: 'https://leetcode.com/problems/product-of-array-except-self/' },
  { name: 'Maximum Subarray', difficulty: 'Medium', topic: 'Arrays & Hashing', link: 'https://leetcode.com/problems/maximum-subarray/' },
  { name: 'Maximum Product Subarray', difficulty: 'Medium', topic: 'Arrays & Hashing', link: 'https://leetcode.com/problems/maximum-product-subarray/' },
  { name: 'Find Minimum in Rotated Sorted Array', difficulty: 'Medium', topic: 'Binary Search', link: 'https://leetcode.com/problems/find-minimum-in-rotated-sorted-array/' },
  { name: 'Search in Rotated Sorted Array', difficulty: 'Medium', topic: 'Binary Search', link: 'https://leetcode.com/problems/search-in-rotated-sorted-array/' },
  { name: '3Sum', difficulty: 'Medium', topic: 'Two Pointers', link: 'https://leetcode.com/problems/3sum/' },
  { name: 'Container With Most Water', difficulty: 'Medium', topic: 'Two Pointers', link: 'https://leetcode.com/problems/container-with-most-water/' },
  { name: 'Sum of Two Integers', difficulty: 'Medium', topic: 'Bit Manipulation', link: 'https://leetcode.com/problems/sum-of-two-integers/' },
  { name: 'Number of 1 Bits', difficulty: 'Easy', topic: 'Bit Manipulation', link: 'https://leetcode.com/problems/number-of-1-bits/' },
  { name: 'Counting Bits', difficulty: 'Easy', topic: 'Bit Manipulation', link: 'https://leetcode.com/problems/counting-bits/' },
  { name: 'Missing Number', difficulty: 'Easy', topic: 'Bit Manipulation', link: 'https://leetcode.com/problems/missing-number/' },
  { name: 'Reverse Bits', difficulty: 'Easy', topic: 'Bit Manipulation', link: 'https://leetcode.com/problems/reverse-bits/' },
  { name: 'Climbing Stairs', difficulty: 'Easy', topic: '1D DP', link: 'https://leetcode.com/problems/climbing-stairs/' },
  { name: 'Coin Change', difficulty: 'Medium', topic: '1D DP', link: 'https://leetcode.com/problems/coin-change/' },
  { name: 'Longest Increasing Subsequence', difficulty: 'Medium', topic: '1D DP', link: 'https://leetcode.com/problems/longest-increasing-subsequence/' },
  { name: 'Longest Common Subsequence', difficulty: 'Medium', topic: '2D DP', link: 'https://leetcode.com/problems/longest-common-subsequence/' },
  { name: 'Word Break', difficulty: 'Medium', topic: '1D DP', link: 'https://leetcode.com/problems/word-break/' },
  { name: 'Combination Sum', difficulty: 'Medium', topic: 'Backtracking', link: 'https://leetcode.com/problems/combination-sum/' },
  { name: 'House Robber', difficulty: 'Medium', topic: '1D DP', link: 'https://leetcode.com/problems/house-robber/' },
  { name: 'House Robber II', difficulty: 'Medium', topic: '1D DP', link: 'https://leetcode.com/problems/house-robber-ii/' },
  { name: 'Decode Ways', difficulty: 'Medium', topic: '1D DP', link: 'https://leetcode.com/problems/decode-ways/' },
  { name: 'Unique Paths', difficulty: 'Medium', topic: '2D DP', link: 'https://leetcode.com/problems/unique-paths/' },
  { name: 'Jump Game', difficulty: 'Medium', topic: 'Greedy', link: 'https://leetcode.com/problems/jump-game/' },
  { name: 'Clone Graph', difficulty: 'Medium', topic: 'Graphs', link: 'https://leetcode.com/problems/clone-graph/' },
  { name: 'Course Schedule', difficulty: 'Medium', topic: 'Graphs', link: 'https://leetcode.com/problems/course-schedule/' },
  { name: 'Pacific Atlantic Water Flow', difficulty: 'Medium', topic: 'Graphs', link: 'https://leetcode.com/problems/pacific-atlantic-water-flow/' },
  { name: 'Number of Islands', difficulty: 'Medium', topic: 'Graphs', link: 'https://leetcode.com/problems/number-of-islands/' },
  { name: 'Longest Consecutive Sequence', difficulty: 'Medium', topic: 'Arrays & Hashing', link: 'https://leetcode.com/problems/longest-consecutive-sequence/' },
  { name: 'Alien Dictionary', difficulty: 'Hard', topic: 'Graphs', link: 'https://leetcode.com/problems/alien-dictionary/' },
  { name: 'Graph Valid Tree', difficulty: 'Medium', topic: 'Graphs', link: 'https://leetcode.com/problems/graph-valid-tree/' },
  { name: 'Number of Connected Components in an Undirected Graph', difficulty: 'Medium', topic: 'Graphs', link: 'https://leetcode.com/problems/number-of-connected-components-in-an-undirected-graph/' },
  { name: 'Insert Interval', difficulty: 'Medium', topic: 'Intervals', link: 'https://leetcode.com/problems/insert-interval/' },
  { name: 'Merge Intervals', difficulty: 'Medium', topic: 'Intervals', link: 'https://leetcode.com/problems/merge-intervals/' },
  { name: 'Non-overlapping Intervals', difficulty: 'Medium', topic: 'Intervals', link: 'https://leetcode.com/problems/non-overlapping-intervals/' },
  { name: 'Meeting Rooms', difficulty: 'Easy', topic: 'Intervals', link: 'https://leetcode.com/problems/meeting-rooms/' },
  { name: 'Meeting Rooms II', difficulty: 'Medium', topic: 'Intervals', link: 'https://leetcode.com/problems/meeting-rooms-ii/' },
  { name: 'Reverse Linked List', difficulty: 'Easy', topic: 'Linked List', link: 'https://leetcode.com/problems/reverse-linked-list/' },
  { name: 'Linked List Cycle', difficulty: 'Easy', topic: 'Linked List', link: 'https://leetcode.com/problems/linked-list-cycle/' },
  { name: 'Merge Two Sorted Lists', difficulty: 'Easy', topic: 'Linked List', link: 'https://leetcode.com/problems/merge-two-sorted-lists/' },
  { name: 'Merge k Sorted Lists', difficulty: 'Hard', topic: 'Linked List', link: 'https://leetcode.com/problems/merge-k-sorted-lists/' },
  { name: 'Remove Nth Node From End of List', difficulty: 'Medium', topic: 'Linked List', link: 'https://leetcode.com/problems/remove-nth-node-from-end-of-list/' },
  { name: 'Reorder List', difficulty: 'Medium', topic: 'Linked List', link: 'https://leetcode.com/problems/reorder-list/' },
  { name: 'Set Matrix Zeroes', difficulty: 'Medium', topic: 'Math & Geometry', link: 'https://leetcode.com/problems/set-matrix-zeroes/' },
  { name: 'Spiral Matrix', difficulty: 'Medium', topic: 'Math & Geometry', link: 'https://leetcode.com/problems/spiral-matrix/' },
  { name: 'Rotate Image', difficulty: 'Medium', topic: 'Math & Geometry', link: 'https://leetcode.com/problems/rotate-image/' },
  { name: 'Word Search', difficulty: 'Medium', topic: 'Backtracking', link: 'https://leetcode.com/problems/word-search/' },
  { name: 'Longest Substring Without Repeating Characters', difficulty: 'Medium', topic: 'Sliding Window', link: 'https://leetcode.com/problems/longest-substring-without-repeating-characters/' },
  { name: 'Longest Repeating Character Replacement', difficulty: 'Medium', topic: 'Sliding Window', link: 'https://leetcode.com/problems/longest-repeating-character-replacement/' },
  { name: 'Minimum Window Substring', difficulty: 'Hard', topic: 'Sliding Window', link: 'https://leetcode.com/problems/minimum-window-substring/' },
  { name: 'Valid Anagram', difficulty: 'Easy', topic: 'Arrays & Hashing', link: 'https://leetcode.com/problems/valid-anagram/' },
  { name: 'Group Anagrams', difficulty: 'Medium', topic: 'Arrays & Hashing', link: 'https://leetcode.com/problems/group-anagrams/' },
  { name: 'Valid Parentheses', difficulty: 'Easy', topic: 'Stack', link: 'https://leetcode.com/problems/valid-parentheses/' },
  { name: 'Valid Palindrome', difficulty: 'Easy', topic: 'Two Pointers', link: 'https://leetcode.com/problems/valid-palindrome/' },
  { name: 'Longest Palindromic Substring', difficulty: 'Medium', topic: '1D DP', link: 'https://leetcode.com/problems/longest-palindromic-substring/' },
  { name: 'Palindromic Substrings', difficulty: 'Medium', topic: '1D DP', link: 'https://leetcode.com/problems/palindromic-substrings/' },
  { name: 'Encode and Decode Strings', difficulty: 'Medium', topic: 'Arrays & Hashing', link: 'https://leetcode.com/problems/encode-and-decode-strings/' },
  { name: 'Maximum Depth of Binary Tree', difficulty: 'Easy', topic: 'Trees', link: 'https://leetcode.com/problems/maximum-depth-of-binary-tree/' },
  { name: 'Same Tree', difficulty: 'Easy', topic: 'Trees', link: 'https://leetcode.com/problems/same-tree/' },
  { name: 'Invert Binary Tree', difficulty: 'Easy', topic: 'Trees', link: 'https://leetcode.com/problems/invert-binary-tree/' },
  { name: 'Binary Tree Maximum Path Sum', difficulty: 'Hard', topic: 'Trees', link: 'https://leetcode.com/problems/binary-tree-maximum-path-sum/' },
  { name: 'Binary Tree Level Order Traversal', difficulty: 'Medium', topic: 'Trees', link: 'https://leetcode.com/problems/binary-tree-level-order-traversal/' },
  { name: 'Serialize and Deserialize Binary Tree', difficulty: 'Hard', topic: 'Trees', link: 'https://leetcode.com/problems/serialize-and-deserialize-binary-tree/' },
  { name: 'Subtree of Another Tree', difficulty: 'Easy', topic: 'Trees', link: 'https://leetcode.com/problems/subtree-of-another-tree/' },
  { name: 'Construct Binary Tree from Preorder and Inorder Traversal', difficulty: 'Medium', topic: 'Trees', link: 'https://leetcode.com/problems/construct-binary-tree-from-preorder-and-inorder-traversal/' },
  { name: 'Validate Binary Search Tree', difficulty: 'Medium', topic: 'Trees', link: 'https://leetcode.com/problems/validate-binary-search-tree/' },
  { name: 'Kth Smallest Element in a BST', difficulty: 'Medium', topic: 'Trees', link: 'https://leetcode.com/problems/kth-smallest-element-in-a-bst/' },
  { name: 'Lowest Common Ancestor of a BST', difficulty: 'Medium', topic: 'Trees', link: 'https://leetcode.com/problems/lowest-common-ancestor-of-a-bst/' },
  { name: 'Implement Trie (Prefix Tree)', difficulty: 'Medium', topic: 'Tries', link: 'https://leetcode.com/problems/implement-trie-prefix-tree/' },
  { name: 'Design Add and Search Words Data Structure', difficulty: 'Medium', topic: 'Tries', link: 'https://leetcode.com/problems/design-add-and-search-words-data-structure/' },
  { name: 'Word Search II', difficulty: 'Hard', topic: 'Tries', link: 'https://leetcode.com/problems/word-search-ii/' },
  { name: 'Find Median from Data Stream', difficulty: 'Hard', topic: 'Heap / Priority Queue', link: 'https://leetcode.com/problems/find-median-from-data-stream/' }
];

const mapped = blind75.map((p, idx) => ({ id: idx + 1, ...p }));
console.log(JSON.stringify(mapped, null, 2));

